nodes = [  
  { :gport => '8080', :hport => '8080',  :hostname => 'test1',  :ip => '192.168.100.10', :box => 'file://../packer/builds/virtualbox-centos7.box', :ram => '1024', :cpus => '1', :desc => 'Centos 7.3 - Post Packer tester'},
#  { :gport => '8080', :hport => '8081',  :hostname => 'appsservr', :ip => '192.168.100.20', :box => 'lastnitescurry/centos7', :ram => '2048', :cpus => '2', :desc => 'Centos 7.3 - linked clone 2'},
#  { :gport => '8080', :hport => '8082',  :hostname => 'jenkins',   :ip => '192.168.100.21', :box => 'lastnitescurry/centos7', :ram => '4096', :cpus => '4', :desc => 'Centos 7.3 - linked clone 3'},
]

Vagrant.configure("2") do |config|

  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = node[:box]
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.network :private_network, ip: node[:ip]
      nodeconfig.vm.network :forwarded_port,  guest: node[:gport],  host: node[:hport]
      memory = node[:ram] ? node[:ram] : 512;
      cpus = node[:cpus] ? node[:cpus] : 1;
      desc = node[:desc] ? node[:desc] : "Please tell me what I am to be";

      nodeconfig.vm.provider :virtualbox do |vb|
        vb.gui = true
        #vb.linked_clone = true
        vb.customize [
          "modifyvm",      :id,
          "--cpus",        cpus.to_s,
          "--memory",      memory.to_s,
          "--name",        node[:hostname].to_s,
          "--description", desc.to_s,
          "--vram",        "256",
        ]
      end
      nodeconfig.vm.provision :shell, :inline => "df -h"
    end
  end

  config.vm.synced_folder("D:/Software", "/software", :mount_options => ["dmode=777","fmode=666"])

end
